const courses = [
  {
    title: 'Complete Web Development Bootcamp',
    description: 'Master HTML, CSS, JavaScript, React, Node.js, and MongoDB in this comprehensive bootcamp. Build real-world projects from scratch and gain the skills employers are looking for. This course covers everything from front-end design to back-end server development, databases, and deployment.',
    instructor: 'Sarah Johnson',
    thumbnail: 'https://placehold.co/600x400/1a73e8/ffffff?text=Web+Development',
    duration: '42 hours',
    lessons: 156,
    category: 'Web Development',
    level: 'Beginner',
    rating: 4.8,
    students: 12450,
    price: 49.99,
  },
  {
    title: 'React - The Complete Guide',
    description: 'Dive deep into React.js including Hooks, Redux, React Router, and Next.js. Learn component architecture, state management patterns, and build production-ready applications. Includes hands-on projects covering real-world scenarios and best practices.',
    instructor: 'Michael Chen',
    thumbnail: 'https://placehold.co/600x400/1557b0/ffffff?text=React+Guide',
    duration: '36 hours',
    lessons: 128,
    category: 'Web Development',
    level: 'Intermediate',
    rating: 4.9,
    students: 9870,
    price: 59.99,
  },
  {
    title: 'Python for Data Science & Machine Learning',
    description: 'Learn Python programming alongside essential data science libraries like NumPy, Pandas, Matplotlib, and Scikit-Learn. Cover statistics, data visualization, machine learning algorithms, and build predictive models from real datasets.',
    instructor: 'Dr. Emily Watson',
    thumbnail: 'https://placehold.co/600x400/2196f3/ffffff?text=Data+Science',
    duration: '28 hours',
    lessons: 98,
    category: 'Data Science',
    level: 'Beginner',
    rating: 4.7,
    students: 15200,
    price: 0,
  },
  {
    title: 'Advanced Machine Learning & AI',
    description: 'Take your machine learning skills to the next level with deep learning, neural networks, NLP, and computer vision. Work with TensorFlow and PyTorch to build advanced AI systems. Includes capstone projects and research paper implementations.',
    instructor: 'Prof. James Miller',
    thumbnail: 'https://placehold.co/600x400/0d47a1/ffffff?text=Machine+Learning',
    duration: '32 hours',
    lessons: 84,
    category: 'Data Science',
    level: 'Advanced',
    rating: 4.6,
    students: 4320,
    price: 79.99,
  },
  {
    title: 'React Native - Build Mobile Apps',
    description: 'Build cross-platform iOS and Android applications using React Native. Learn navigation, state management, native modules, and app deployment. Create beautiful, performant mobile apps with a single JavaScript codebase.',
    instructor: 'Alex Rivera',
    thumbnail: 'https://placehold.co/600x400/1565c0/ffffff?text=React+Native',
    duration: '24 hours',
    lessons: 76,
    category: 'Mobile Development',
    level: 'Intermediate',
    rating: 4.5,
    students: 6780,
    price: 44.99,
  },
  {
    title: 'Flutter Mobile Development Masterclass',
    description: 'Master Flutter and Dart to create stunning mobile applications for both iOS and Android. Learn widget composition, state management with Provider and Riverpod, animations, and Firebase integration for full-stack mobile development.',
    instructor: 'Priya Sharma',
    thumbnail: 'https://placehold.co/600x400/1976d2/ffffff?text=Flutter+Dev',
    duration: '20 hours',
    lessons: 64,
    category: 'Mobile Development',
    level: 'Beginner',
    rating: 4.7,
    students: 8540,
    price: 0,
  },
  {
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of user interface and user experience design. Master design thinking, wireframing, prototyping, and usability testing. Work with industry-standard tools and build a professional design portfolio from scratch.',
    instructor: 'Lisa Park',
    thumbnail: 'https://placehold.co/600x400/42a5f5/ffffff?text=UI+UX+Design',
    duration: '16 hours',
    lessons: 52,
    category: 'Design',
    level: 'Beginner',
    rating: 4.8,
    students: 11200,
    price: 34.99,
  },
  {
    title: 'Advanced Figma for Professional Designers',
    description: 'Master Figma from advanced components and auto-layout to design systems and team collaboration. Learn advanced prototyping, plugins, and workflow optimization. Perfect for designers looking to level up their Figma expertise.',
    instructor: 'David Kim',
    thumbnail: 'https://placehold.co/600x400/1e88e5/ffffff?text=Figma+Pro',
    duration: '14 hours',
    lessons: 44,
    category: 'Design',
    level: 'Advanced',
    rating: 4.4,
    students: 3200,
    price: 39.99,
  },
  {
    title: 'Digital Marketing Strategy',
    description: 'Learn SEO, social media marketing, email campaigns, content strategy, and paid advertising. Understand analytics and conversion optimization to drive real business results. Includes case studies from successful marketing campaigns.',
    instructor: 'Rachel Torres',
    thumbnail: 'https://placehold.co/600x400/2962ff/ffffff?text=Digital+Marketing',
    duration: '18 hours',
    lessons: 62,
    category: 'Marketing',
    level: 'Intermediate',
    rating: 4.5,
    students: 7650,
    price: 0,
  },
  {
    title: 'Business Analytics & Strategy',
    description: 'Develop strategic thinking and analytical skills for business success. Learn data-driven decision making, competitive analysis, financial modeling, and business intelligence tools. Perfect for aspiring managers and entrepreneurs.',
    instructor: 'Robert Chang',
    thumbnail: 'https://placehold.co/600x400/0277bd/ffffff?text=Business+Analytics',
    duration: '22 hours',
    lessons: 72,
    category: 'Business',
    level: 'Intermediate',
    rating: 4.6,
    students: 5430,
    price: 54.99,
  },
];

export default courses;
